name: CD

on:
  push:
    tags:
      - '*'

env:
  PY_VERSION: 3.11

jobs:
  pypi-build:
    name: Build package for PyPI
    if: github.repository == 'dougiesquire/payu'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PY_VERSION }}

      - run: |
          python3 -m pip install --upgrade build && python3 -m build

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist

  pypi-publish:
    # Split build and publish to restrict trusted publishing to just this workflow
    needs: ['pypi-build']
    name: Publish to TestPyPI.org
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifact/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@2f6f737ca5f74c637829c0f5c3acd0e29ea5e8bf # v1.8.11
        with:
          packages-dir: artifact/
          repository-url: https://test.pypi.org/legacy/

  # conda:
  #   name: Build with conda and upload
  #   if: github.repository == 'payu-org/payu'
  #   runs-on: ubuntu-latest
  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     - name: Checkout source
  #       uses: actions/checkout@v4

  #     - name: Setup conda environment
  #       uses: conda-incubator/setup-miniconda@11b562958363ec5770fef326fe8ef0366f8cbf8a # v3.0.1
  #       with:
  #         miniconda-version: "latest"
  #         python-version: ${{ env.PY_VERSION }}
  #         environment-file: conda/environment.yml
  #         auto-update-conda: false
  #         auto-activate-base: false
  #         show-channel-urls: true

  #     - name: Build and upload the conda package
  #       uses: uibcdf/action-build-and-upload-conda-packages@c6e7a90ad5e599d6cde76e130db4ee52ad733ecf # v1.2.0
  #       with:
  #         meta_yaml_dir: conda
  #         python-version: ${{ env.PY_VERSION }}
  #         user: accessnri
  #         label: main
  #         token: ${{ secrets.anaconda_token }}
